<?php
    require_once("classes/database.php");
    require_once("classes/database_utils.php");            
    require_once("classes/form_validate.php");
    require_once("classes/file.php");
    require_once("classes/autenticacao.php");
    require_once("functions.php");

    $STATUS_PEDIDO_REJEITADO = 1;
    $STATUS_PEDIDO_AGENDADO = 2;
    $STATUS_PEDIDO_CANCELADO = 3;
    $STATUS_PEDIDO_AGUARDANDO_CONFIRMACAO_LOCAL_RETIRADA = 4;
    $STATUS_PEDIDO_AGUARDANDO_CONFIRMACAO_RETIRADA = 5;
    $STATUS_PEDIDO_AGUARDANDO_CONFIRMACAO_LOCAL_ENTREGA = 6;
    $STATUS_PEDIDO_AGUARDANDO_CONFIRMACAO_ENTREGA = 7;
    $STATUS_PEDIDO_AGUARDANDO_DEFINICAO_PENDENCIAS = 8;
    $STATUS_PEDIDO_AGUARDANDO_CONFIRMACAO_PENDENCIAS = 9;
    $STATUS_PEDIDO_PENDENCIAS_ACEITAS = 10;
    $STATUS_PEDIDO_PENDENCIAS_RECUSADAS = 11;
    $STATUS_PEDIDO_AGUARDANDO_PAGAMENTO_PENDENCIAS = 12;
    $STATUS_PEDIDO_AGUARDANDO_CONFIRMACAO_PAGAMENTO_PENDENCIAS = 13;
    $STATUS_PEDIDO_PENDENCIAS_PAGAS_CARTAO_CREDITO = 14;
    $STATUS_PEDIDO_PENDENCIAS_PAGAS_DINHEIRO = 15;
    $STATUS_PEDIDO_CONCLUIDO = 16;
?>