<?php
    require_once("classes/database.php");
    require_once("classes/database_utils.php");
    require_once("classes/tbl_assunto.php");
    require_once("classes/tbl_usuario.php");
    require_once("classes/tbl_sobre_empresa.php");
    require_once("classes/tbl_empreste.php");
    require_once("classes/form_validate.php");
    require_once("classes/file.php");
    require_once("functions.php");
?>