<?php
    require_once("classes/database.php");
    require_once("classes/database_utils.php");
    require_once("classes/tbl_assunto.php");
    require_once("classes/tbl_usuario.php");
    require_once("classes/tbl_sobre_empresa.php");
    require_once("classes/tbl_empreste.php");
    require_once("classes/tbl_sobre_projeto.php");
    require_once("classes/tbl_beneficios_projeto.php");
    require_once("classes/tbl_usuario_cs.php");
    require_once("classes/tbl_nivel_acesso_cs.php");
    require_once("classes/tbl_permissao_cs.php");
    require_once("classes/tbl_home.php");
    require_once("classes/tbl_perguntas_frequentes.php");
    require_once("classes/tbl_fale_conosco.php");
    require_once("classes/form_validate.php");
    require_once("classes/file.php");
    require_once("classes/autenticacao.php");
    require_once("functions.php");
?>